apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:HnZ0I01yCQQ7hzq9t1JgGAPvSKQPRIbOjr4Up0mIExQkZHowkPb4J/wejPyQf8utrQlouPrfShfSCV+kv4PBPto=,iv:40PZ3hQYWLegoyzmxR4UAc5Y680prHdMbvkwz9sDMjk=,tag:yjnAGkH5dOkEXLtJ29M6Aw==,type:comment]
    #ENC[AES256_GCM,data:pjraWUw486wwXcIXHhUPAUfq9SOD5EKolccJwnqdZ5i8w47+SBbMYG27qNc=,iv:/qPALTcJmXkY28uE5zLcj2WjoinIF1uuN/gRPPYxAkM=,tag:EkbCcVIDkTZxhtbjWdFhEA==,type:comment]
    VIP: ENC[AES256_GCM,data:6WSWwby5idEmnc3q/3Q=,iv:8sBWOshtUKko6IN0eD7891AxGXD5qzzyj3KCnakqIIU=,tag:3twJgXhO37wrBui8qe3N7Q==,type:str]
    #ENC[AES256_GCM,data:aGG2FoyPgeSraJhNT/yp/Whlsi0PjjrAnYk=,iv:XcLYghM1VaXaahIB7jeT7WqK2Cwx1De8TEKUWnr1Ch4=,tag:tfpQ52Q6f2w8psNdHbxeLg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:8Jryrc+6S1OMKCNqghw=,iv:Gz+lXfGpaycGV0p7Wb2hG56HCYXuQaj1MiiHHLOvv7Q=,tag:/rL21cnO+MXxPnAKwBL3fA==,type:str]
    #ENC[AES256_GCM,data:m0+Oor2FgWZxH+PuNnuZdulVNR+ZWlaFRgm9SbwK5aS3Zg==,iv:nIt2dbzQpxNGhsGyXOlPlPcm8vPNtjdDBczod2wItnY=,tag:oomzmpj2r257LkBg1mxMXA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:8XmbWqBbnZuz8eQV,iv:pVJvuOmbqihCqluP4T3bfhlQ9l0j34d/aPMgcsRSmY0=,tag:E4DDFm2YoYDEpcHm4tOD3g==,type:str]
    #ENC[AES256_GCM,data:mzoH1R/UPJ87qxF6DoXjCq0T9nKyISnvmo4XOyMaIvajVyf/4chVOg5WOGlECq4=,iv:L+3jrfF62FgbNhiRR7fsj2ffxTdruXvrcWQHZHACDnM=,tag:IrpCQvMQ4uO+jg/kJtzL0Q==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:m8nXRalaHdgLeDLWpRMRPnZwENRsJnhgiZ2qxXE=,iv:5zNbSeLumtDuE52k4LjKcs5/iNz5Ho0W6QdxkPoavok=,tag:33N+AOINlpc4ULdD8IOPvw==,type:str]
    #ENC[AES256_GCM,data:hUftpjEvEkYO186LcSgnO/o62kM/aYFNFN8j/9Hngluj8Uq1Dx+jy/LD0k8OUkNKt1RZ+h9oqt75TYVPfaOfDHBXVdboEagVixbzc24SNhs=,iv:acVbHjeaCgasemDXFQ9wuWL2mMKjQ1kreySjy+NQ3O4=,tag:M1yi9u4i3SKUdropm9x7Cw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:AHFrPVV3MS1sJN2zzIk=,iv:0G31vE2HP9P5g+18NCc96myxInog3QlyZq4z/5dfwco=,tag:BZ0KZb6odW9nCxecHcsZOQ==,type:str]
    #ENC[AES256_GCM,data:YUUaXLPTfM+TdJb9cVmdYdX/jYUqpePQu3BQDfoLCELUGxwj9TkgK/Br7rRwMduthi/AS5BtsQmrA+9LXY8+OB4Pblc=,iv:bFXmUBu5Rck5U9/TQosCpZGSHwmbF7AXEnO2GY4SsJM=,tag:nMqTixUYQtFYR0GSyP8s+Q==,type:comment]
    KUBEAPPS_IP: ENC[AES256_GCM,data:/flC3ZBdiwEYfdNhqiQ=,iv:INoAgitFN2jOYQ/q1xqVDeIyz4smfh9EcInIX6BcYJY=,tag:LNgWqLuE0wBIuaDquFq4mw==,type:str]
    #ENC[AES256_GCM,data:UqM6y4DjwSs25zMwlcfPH79lTpt4d+8BnjSjHLh9RV4DNHb0wjUknEQeFx/zAJmN1sBRnun1ehQ=,iv:mTAz3FrAnr07HJeZajCQ8Ratgrc9PRPzOgFr3REAaaE=,tag:QUUqFPe7KU/rDiK8upgWFA==,type:comment]
    #ENC[AES256_GCM,data:BcBwps/D6zUZ0X3Slcr+ohWVOOSNyCpIHQ==,iv:nmhn500yydnlQaU81In3hKfM6NX2nxtKR2q6NPpbxqg=,tag:IrUqkDqnhKH1lKhADTll+A==,type:comment]
    GITHUB_REPOSITORY: ""
    #ENC[AES256_GCM,data:zg1bVgBbm6mdflKdig==,iv:i88v64iNPi4O8ll4laUiI3lLgIgkP5rII9qssUhkE5E=,tag:1Ya+d9IcFyJ7GpscbiA6MA==,type:comment]
    PODNET: ENC[AES256_GCM,data:SJPHnx8X7CT0uPXiuw==,iv:GI/vJn4PKaExg89+Gpl75yAJ6wpJpi575WSl8mMJIhI=,tag:J6oKvRurzOPEJm3BlNwvLA==,type:str]
    SVCNET: ENC[AES256_GCM,data:sWMaxv2xTUwemzC0+A==,iv:58v0B63hTywL1fO5N+G+vUjrcN6A8n5CHz221rhZ6YI=,tag:cjx8C/b6suxbv1PDTibUGw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jf3ge2wr5qfktw2hg6g973ms3ts8262mdvdgrl6nr7zhx99npeeswwflkn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUmF4VXB0RE5kMVI2M05N
            aGF0TDIydERNdGx5UzIwaHk1OU9YUm13U1ZvCjNRZGpDKzRDckZhZFIxOTkwUjRZ
            Y1VsUkVzV1JRSWdpeUVYYWl6TTdTRVEKLS0tIFh2YWhWbHdrMmtTNkxEbjkxbnJM
            NHQ0WXdSbDBEY1owcFcxT0JGa3lhTEUKQ5/zw7Up8Qz4/pqxSps3SkkUkWeYebNK
            tH5hPNUIN0Krl908LlqSIKXyopS5zkJQ8JBuVV1YBL8Dj0QZ3cG5OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-18T17:01:37Z"
    mac: ENC[AES256_GCM,data:gtnQIlSFaM4UxkSvb0huDSwaEO+9l2r1NQ5OistkeRXedEQAUDrBBENGPbEXLT9K1lhY3C+oNOjabXcaDwlqim5r6c6HLlLJr45+vbJCCS4dG5teJSINT7dRplTlFaUnNImd/gc0dJ1XdZkJpmu6L0T4A9/PU4f3XfgpCvWumPA=,iv:+hBYp9IJT1MzOeQUf5o9A/a+msb+tZAbR1GU2NfAdKw=,tag:fIh2t0sfYw5A/9TKriaNAQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
